{*
===============================================================================
phpMyProfiler Theme "Bstrap"
-------------------------------------------------------------------------------
Release:    0.4.003
Date:       2014-04-27
Author:     George Lewe (george@lewe.com)
Copyright:  (c) 2014. All rights reserved.
-------------------------------------------------------------------------------

header.tpl

===============================================================================
*}

<!DOCTYPE html>
<!--[if true]>
===============================================================================
{t}Generated by{/t} phpMyProfiler {$pmp_version}
_______________________________________________________________________________

Theme:      Bstrap
Release:    0.4.003
Date:       2014-04-27
Author:     George Lewe
Copyright:  (c) 2014. All rights reserved.
License:    LGPL v3
===============================================================================
<![endif]-->
<html lang="en">
   <head>
      <title>phpMyProfiler Administration</title>
      
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta charset="utf-8">
      <meta name="robots" content="noindex, nofollow">
      <link rel="shortcut icon" href="favicon.ico">

      <link rel="stylesheet" media="screen" href="../themes/bstrap/css/admin/jqueryui.css" type="text/css">

      <!-- Standard Bootstrap CSS -->
      <link rel="stylesheet" href="../themes/bstrap/css/bootstrap.css/css/bootstrap.min.css" type="text/css" media="screen">
      <link rel="stylesheet" href="../themes/bstrap/css/bootstrap.css/css/bootstrap-theme.min.css" type="text/css" media="screen">
      <!-- Custom CSS add ons by George -->
      <link rel="stylesheet" href="../themes/bstrap/css/bootstrap.css/css/bootstrap-submenu.min.css" type="text/css" media="screen">
      <link rel="stylesheet" href="../themes/bstrap/css/bstrap/bstrap.css" type="text/css" media="screen">
      <!-- Personal CSS Overwrites for the user -->
      <link rel="stylesheet" href="../themes/bstrap/css/bstrap/custom.css" type="text/css" media="screen">
      
      <script type="text/javascript" src="../js/jquery.js"></script>
      <script type="text/javascript" src="../js/jqueryui.js"></script>
      <script type="text/javascript" src="../js/jquery.mousewheel.js"></script>
      <script type="text/javascript" src="../js/functions.js"></script>
      <script type="text/javascript" src="../js/overlib.js"></script>

      <!-- Fancybox 2 -->
      <!-- Add fancyBox main JS and CSS files -->
      <script type="text/javascript" src="../themes/bstrap/fancybox2/jquery.fancybox.js?v=2.1.5"></script>
      <link rel="stylesheet" type="text/css" href="../themes/bstrap/fancybox2/jquery.fancybox.css?v=2.1.5" media="screen">
      <!-- Add Button helper (this is optional) -->
      <link rel="stylesheet" type="text/css" href="../themes/bstrap/fancybox2/helpers/jquery.fancybox-buttons.css?v=1.0.5">
      <script type="text/javascript" src="../themes/bstrap/fancybox2/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>
      <!-- Add Thumbnail helper (this is optional) -->
      <link rel="stylesheet" type="text/css" href="../themes/bstrap/fancybox2/helpers/jquery.fancybox-thumbs.css?v=1.0.7">
      <script type="text/javascript" src="../themes/bstrap/fancybox2/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>
      <!-- Add Media helper (this is optional) -->
      <script type="text/javascript" src="../themes/bstrap/fancybox2/helpers/jquery.fancybox-media.js?v=1.0.6"></script>
      
      <!-- HTML5 shiv and Respond.js IE8 support of HTML5 elements and media queries -->
      <!--[if lt IE 9]>
         <script src="../themes/{$pmp_theme}/bootstrap/js/html5shiv.js"></script>
         <script src="../themes/{$pmp_theme}/bootstrap/js/respond.min.js"></script>
      <![endif]-->
       
      {if isset($Focus)}
         {literal}
            <script type="text/javascript">
               function FocusField()
               {
                  document.formular.{/literal}{$Focus}{literal}.select();
                  document.formular.{/literal}{$Focus}{literal}.focus();
               }
            </script>
         {/literal}
      {/if}
      
   </head>

   <body {if isset($Focus) && $Focus} onload="FocusField();"{/if}>
   
      <noscript><div>{t}Please activate JavaScript for all functions!{/t}</div></noscript>
   
      <!--[if lt IE 7]>
         <div style='border: 1px solid #F7941D; background: #FEEFDA; text-align: center; clear: both; height: 75px; position: relative;'>
            <div style='position: absolute; right: 3px; top: 3px; font-family: courier new; font-weight: bold;'><a href='#' onclick='javascript:this.parentNode.parentNode.style.display="none"; return false;'><img src='themes/default/images/noie6/ie6nomore-cornerx.jpg' style='border: none;' alt='Close this notice'></a></div>
            <div style='width: 750px; margin: 0 auto; text-align: left; padding: 0; overflow: hidden; color: black;'>
               <div style='width: 75px; float: left;'><img src='themes/default/images/noie6/ie6nomore-warning.jpg' alt='Warning!'></div>
               <div style='width: 275px; float: left; font-family: Arial, sans-serif;'>
                  <div style='font-size: 14px; font-weight: bold; margin-top: 12px;'>You are using an outdated browser</div>
                  <div style='font-size: 12px; margin-top: 6px; line-height: 12px;'>For a better experience using this site, please upgrade to a modern web browser.</div>
               </div>
               <div style='width: 75px; float: left;'><a href='http://www.firefox.com'><img src='themes/default/images/noie6/ie6nomore-firefox.jpg' style='border: none;' alt='Get Firefox 3.5'></a></div>
               <div style='width: 75px; float: left;'><a href='http://www.browserforthebetter.com/download.html'><img src='themes/default/images/noie6/ie6nomore-ie8.jpg' style='border: none;' alt='Get Internet Explorer 8'></a></div>
               <div style='width: 73px; float: left;'><a href='http://www.apple.com/safari/download/'><img src='themes/default/images/noie6/ie6nomore-safari.jpg' style='border: none;' alt='Get Safari 4'></a></div>
               <div style='width: 70px; float: left;'><a href='http://www.google.com/chrome'><img src='themes/default/images/noie6//ie6nomore-chrome.jpg' style='border: none;' alt='Get Google Chrome'></a></div>
               <div style='float: left;'><a href='http://www.opera.com/browser/download/'><img src='themes/default/images/noie6/ie6nomore-opera.jpg' style='border: none;' alt='Get Opera'></a></div>
            </div>
         </div>
      <![endif]-->

      {if !isset($nohead)}
         <!-- ==================================================================== 
         NAVBAR 
         -->
         <header class="navbar navbar-inverse navbar-fixed-top">
            <form action="login.php?{$session}" method="post" target="_self">
               <div class="container">
                  <div class="navbar-header">
                     <a href="index.php?{$session}" class="navbar-brand" style="padding: 6px 0 0 0;"><img src="../themes/{$pmp_theme}/images/logo.png" alt="" title="Admin Homepage"></a>
                     <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                        <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                     </button>
                  </div>
                  <div class="navbar-collapse collapse" id="navbar-main">
                     <ul class="nav navbar-nav">
                        {if !isset($nologout)}
                           <li><a tabindex="-1" href="index.php?{$session}">{t}Admin Home{/t}</a></li>
                           <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#" id="common">{t}Common preferences{/t}<span class="caret"></span></a>
                              <ul class="dropdown-menu" aria-labelledby="common">
                                 <li><a tabindex="-1" href="preferences.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/config_s.png" alt="">&nbsp;&nbsp;{t}Preferences{/t}</a></li>
                                 <li><a tabindex="-1" href="passwd.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/passwd_s.png" alt="">&nbsp;&nbsp;{t}Change password{/t}</a></li>
                                 <li><a tabindex="-1" href="phpinfo.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/phpinfo_s.png" alt="">&nbsp;&nbsp;{t}Call PHP-info{/t}</a></li>
                              </ul>
                           </li>
                           <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#" id="refresh">{t}Refresh data{/t}<span class="caret"></span></a>
                              <ul class="dropdown-menu" aria-labelledby="refresh">
                                 <li><a tabindex="-1" href="parse.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/parse_s.png" alt="">&nbsp;&nbsp;{t}New collection{/t}</a></li>
                                 <!-- Coverflow for later implementation <li><a tabindex="-1" href="coverflow.php?{$session}">{t}Coverflow{/t}</a></li> -->
                                 <li><a tabindex="-1" href="updateawards.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/updateawards_s.png" alt="">&nbsp;&nbsp;{t}Update awards{/t}</a></li>
                                 <li><a tabindex="-1" href="updaterates.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/updaterates_s.png" alt="">&nbsp;&nbsp;{t}Exchange rates{/t}</a></li>
                                 {if !isset($nomovies)}<li><a tabindex="-1" href="updateimdb.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/updateimdb_s.png" alt="">&nbsp;&nbsp;{t}Update external reviews{/t}</a></li>{/if}
                              </ul>
                           </li>
                           <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#" id="additional">{t}Additional functions{/t}<span class="caret"></span></a>
                              <ul class="dropdown-menu" aria-labelledby="additional">
                                 <li><a tabindex="-1" href="news.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/news_s.png" alt="">&nbsp;&nbsp;{t}News{/t}</a></li>
                                 <li><a tabindex="-1" href="pictures.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/photos_s.png" alt="">&nbsp;&nbsp;{t}Collection Pictures{/t}</a></li>
                                 {if isset($gbfound)}<li><a tabindex="-1" href="guestbook.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/guestbook_s.png" alt="">&nbsp;&nbsp;{t}Guestbook{/t}</a></li>{/if}
                                 {if !isset($nomovies)}
                                    <li><a tabindex="-1" href="reviews.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/reviews_s.png" alt="">&nbsp;&nbsp;{t}Reviews{/t}</a></li>
                                    <li><a tabindex="-1" href="nocover.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/nocover_s.png" alt="">&nbsp;&nbsp;{t}Check pictures of covers{/t}</a></li>
                                    <li><a tabindex="-1" href="screenshots.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/screenshots_s.png" alt="">&nbsp;&nbsp;{t}Screenshots{/t}</a></li>
                                    <li><a tabindex="-1" href="report.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/report_s.png" alt="">&nbsp;&nbsp;{t}Print listing{/t}</a></li>
                                 {/if}
                                 <li><a tabindex="-1" href="update.php?{$session}" {if isset($StandDB) && $StandDB < $StandUpdate}style="border-color:red"{/if}><img src="../themes/{$pmp_theme}/images/menu/update_s.png" alt="">&nbsp;&nbsp;{t}Refresh database{/t}</a></li>
                                 <li><a tabindex="-1" href="checklang.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/checklang_s.png" alt="">&nbsp;&nbsp;{t}Check translations{/t}</a></li>
                              </ul>
                           </li>
                        {/if}
                     </ul>
                     <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#" id="phpmyprofiler">phpMyProfiler<span class="caret"></span></a>
                           <ul class="dropdown-menu" aria-labelledby="phpmyprofiler">
                              <li><a tabindex="-1" href="index.php?{$session}"><img src="../themes/{$pmp_theme}/images/menu/home_admin_s.png" alt="">&nbsp;&nbsp;{t}Admin Home{/t}</a></li>
                              <li><a href="../index.php"><img src="../themes/{$pmp_theme}/images/menu/home_s.png" alt="">&nbsp;&nbsp;{t}Frontend Home{/t}</a></li>
                              <li class="divider"></li>
                              <li><a tabindex="-1" href="http://www.phpmyprofiler.de"><img src="../themes/{$pmp_theme}/images/menu/internet_s.png" alt="">&nbsp;&nbsp;{t}phpMyProfiler Home{/t}</a></li>
                              <li><a tabindex="-1" href="http://forum.phpmyprofiler.de"><img src="../themes/{$pmp_theme}/images/menu/internet_s.png" alt="">&nbsp;&nbsp;{t}phpMyProfiler Forum{/t}</a></li>
                           </ul>
                        </li>
                     </ul>
                  </div>
               </div>
            </form>
         </header> <!-- NAVBAR -->

         <header class="navbar" style="background: #ffb300; padding-top: 56px; padding-bottom: 0px; margin-bottom: 0px;">
         </header>

         <header class="well" style="padding-top: 4px; padding-bottom: 4px;">
            <div class="container text-right">
               <form action="login.php?{$session}" method="post" target="_self">
                  {if isset($header)}
                     {if $header_img == "upload"}<button type="button" class="btn btn-default" name="backParsing" onclick="window.location='parse.php?{$session}';"><img src="../themes/{$pmp_theme}/images/menu/parse_s.png" alt="">&nbsp;&nbsp;{t}Back to parsing menu...{/t}</button>&nbsp;{/if}
                     {if $header_img == "uploadcsv"}<button type="button" class="btn btn-default" name="backUpdateAwards" onclick="window.location='updateawards.php?{$session}';"><img src="../themes/{$pmp_theme}/images/menu/updateawards_s.png" alt="">&nbsp;&nbsp;{t}Back to award menu...{/t}</button>&nbsp;{/if}
                     {if $header_img == "getcover"}<button type="button" class="btn btn-default" name="backCover" onclick="window.location='nocover.php?{$session}';"><img src="../themes/{$pmp_theme}/images/menu/nocover_s.png" alt="">&nbsp;&nbsp;{t}Back to Cover overview{/t}</button>&nbsp;{/if}
                     {if $header_img == "getheadshot"}<button type="button" class="btn btn-default" name="backHeadshots" onclick="window.location='headshot.php?{$session}';">{t}Back to headshots{/t}</button>&nbsp;{/if}
                     {if $header_img == "screenshots" && isset($show) && $show == 1}<button type="button" class="btn btn-default" name="backScreenshots" onclick="window.location='screenshots.php?{$session}';"><img src="../themes/{$pmp_theme}/images/menu/screenshots_s.png" alt="">&nbsp;&nbsp;{t}Back to screenshots{/t}</button>&nbsp;{/if}
                     {if isset($editadd)}<button type="button" class="btn btn-default" name="backNews" onclick="window.location='news.php?{$session}';"><img src="../themes/{$pmp_theme}/images/menu/news_s.png" alt="">&nbsp;&nbsp;{t}Back to the News{/t}</button>&nbsp;{/if}
                     <button type="button" class="btn btn-default" name="backAdmin" onclick="window.location='index.php?{$session}';"><img src="../themes/{$pmp_theme}/images/menu/config_s.png" alt="">&nbsp;&nbsp;{t}Back to admin menu{/t}</button>
                  {/if}
                  {if !isset($nologout)}
                     <input name="logout" type="text" value="true" style="visibility:hidden; width:0px;">
                     <button type="submit" class="btn btn-warning" name="logout"><img src="../themes/{$pmp_theme}/images/menu/logout_s.png" alt="">&nbsp;&nbsp;{t}Logout{/t}</button>
                  {/if}
               </form>
            </div>
         </header>
   
      {else}
         <div class="container">
            <div class="container">
               <a href="javascript:window.close()">{t}Close{/t}</a>
            </div>
         </div>
      {/if}

      <!-- ==================================================================== 
      CONTAINER 
      -->
      <div class="container" {if !isset($nohead) && !isset($header)}style="padding-top: 0px;"{/if}>
