{*
===============================================================================
phpMyProfiler Theme "Bstrap"
-------------------------------------------------------------------------------
Release:    0.4.003
Date:       2014-04-27
Author:     George Lewe (george@lewe.com)
Copyright:  (c) 2014. All rights reserved.
-------------------------------------------------------------------------------

report_list.tpl

===============================================================================
*}

{include file="admin/header.tpl"}

<div class="col-lg-12">

   <div class="panel panel-primary">
      <div class="panel-heading">{t}Print listing{/t}</div>
      <div class="panel-body">

         <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
               <thead>
                  <tr>
                     {foreach from=$headers item=header}
                        <th>{$header}</th>
                     {/foreach}
                  </tr>
               </thead>
               <tbody>
                  {foreach from=$data item=col}
                     <tr>
                        {foreach from=$col item=field}<td>{$field}</td>{/foreach}
                     </tr>
                  {/foreach}
                  <tr>
                     <td colspan="{$data.0|@count}" class="text-right small">{t}Generated by{/t} phpMyProfiler {$pmp_version}</td>
                  </tr>
               </tbody>
            </table>
         </div>
         
      </div>
   </div>
   
</div>

{include file="admin/footer.tpl"}
