{include file="admin/header.tpl"}

<div id="mainpanel">
    <table cellspacing="0" cellpadding="0" border="0" class="tabelle">
	<tr>
	    {foreach from=$headers item=header}
		<th>{$header}</th>
	    {/foreach}
	</tr>
	{foreach from=$data item=col}
	    <tr>
		{foreach from=$col item=field}
		    <td>{$field}</td>
		{/foreach}
	    </tr>
	{/foreach}
	<tr>
	    <td colspan="{$data.0|@count}" style="text-align:right"><small><br />{t}Generated by{/t} phpMyProfiler {$pmp_version}</small></td>
	</tr>
    </table>
</div>

{include file="admin/footer.tpl"}
